### ISSUE TITLE
A question about how this works.

### ISSUE THREAD

**Issue by h2nwy30y** [Gabattal/scripts#3]
So I'm looking at how you are picking champs and it seems to be here, https://github.com/Gabattal/Scripts-LeagueOfLegends/blob/8fa6708d01117e2a01d993ab03f4fb2700abb619/Auto-Champ-Select/Auto-Champ-Select-LCU/main.py#L88 But I don't quite understand where the value for action_id comes from.

I see that it comes from `event.data['actions']` with `event` being variable passed in from calling what seems to be a function? (i don't know python) https://github.com/Gabattal/Scripts-LeagueOfLegends/blob/8fa6708d01117e2a01d993ab03f4fb2700abb619/Auto-Champ-Select/Auto-Champ-Select-LCU/main.py#L52 But I don't see where it is being called from..

Hoping i could get some help on this

**Comment by Gabattal** [comment]
Hi ! It's not really about Python but mainly about LCU (the package I am using for this script)
You will find your answer [here](https://lcu-driver.readthedocs.io/en/latest/quickstart.html) in the websocket part ;)
